resources:
  - name: pull_request
    type: GitRepo
    configuration:
      gitProvider: github_wakingrufus
      path: wakingrufus/kalibrate
      buildOn:
        commit: true
        pullRequestCreate: true
      cancelPendingRunsOn:
        newCommit: true
        pullRequestUpdate: true
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrog

pipelines:
  - name: kalibrate_build
    steps:
      - name: build
        type: GradleBuild
        configuration:
          gradleCommand: "build"
          useWrapper: true
          autoPublishBuildInfo: true
          forceXrayScan: true
          inputResources:
            - name: pull_request
          outputResources:
            - name: build_info
          integrations:
            - name: jfrog
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"